<?php

use Hasan\Tagme\TaggyServiceProvider;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;

abstract class TestCase extends \Orchestra\Testbench\TestCase
{
	use RefreshDatabase;

	/**
	 * @param \Illuminate\Foundation\Application $app
	 * @return string[]
	 */
	protected function getPackageProviders($app): array
	{
		return [TaggyServiceProvider::class];
	}

	/**
	 * Setup everything before test
	 */
	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		// Stop Mass Assignment Exception
		Model::unguard();

		// Migrate database
		$this->artisan('migrate', [
			'--database' => 'testbench',
			'--realpath' => realpath(__DIR__ . '/../migrations')
		]);
	}

	/**
	 * Setup everything after test
	 */
	protected function tearDown(): void
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	protected function getEnvironmentSetUp($app)
	{
		$app['config']->set('database.default', 'testbench');
		$app['config']->set('database.connections.testbench', [
			'driver' => 'sqlite',
			'database' => ':memory:',
			'prefix' => ''
		]);

		Schema::create('lessons', function (Blueprint $table) {
			$table->id();
			$table->string('title');
			$table->timestamps();
		});
	}
}
